
VERSION_PRODUCT     = $(VERSION_PRODUCT)
VERSION_MAJOR       = $(VERSION_MAJOR)
VERSION_MINOR       = $(VERSION_MINOR)
VERSION_MAINTENANCE = $(VERSION_MAINTENANCE)
VERSION_PATCH       = $(VERSION_PATCH)

COMPILER=VS2013

CSSUBTARGET = PurgeUser

# Define the objects of the target module
SRC = \
 	Properties/AssemblyInfo.cs \
	Program.cs \

# Define the custom header include path
CSINCPATH = \

# Define the custom library path
CSLIBPATH = \

CSLIBS = \



